FROM rust:1.88 AS builder

ARG PACKAGE_NAME
ARG BIN_NAME

WORKDIR /app
COPY services/ /app/

RUN cargo build --release -p ${PACKAGE_NAME}

FROM debian:bookworm-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates \
    && rm -rf /var/lib/apt/lists/*

ARG BIN_NAME
WORKDIR /app
COPY --from=builder /app/target/release/${BIN_NAME} /app/${BIN_NAME}
ENV BIN_NAME=${BIN_NAME}

EXPOSE 8000
CMD ["/bin/sh", "-lc", "/app/$BIN_NAME"]
