-- user settings columns
ALTER TABLE users ADD COLUMN IF NOT EXISTS default_currency VARCHAR(10);
ALTER TABLE users ADD COLUMN IF NOT EXISTS timezone VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS language VARCHAR(10);
ALTER TABLE users ADD COLUMN IF NOT EXISTS theme VARCHAR(10);
