#!/usr/bin/env python3
import json
import random
import urllib.error
import urllib.request
from datetime import datetime, timedelta, timezone

BASE_URL = "http://localhost:18000/api/v1"
OWNER_USERNAME = "codex_test_user"
OWNER_PASSWORD = "testpass123"
DEMO_PASSWORD = "testpass123"

DEMO_USERS = [
    {"username": "demo_alice", "email": "demo_alice@example.com", "full_name": "Alice Chen"},
    {"username": "demo_bob", "email": "demo_bob@example.com", "full_name": "Bob Wang"},
    {"username": "demo_cindy", "email": "demo_cindy@example.com", "full_name": "Cindy Li"},
    {"username": "demo_david", "email": "demo_david@example.com", "full_name": "David Zhou"},
    {"username": "demo_emma", "email": "demo_emma@example.com", "full_name": "Emma Sun"},
]


def api_request(method, path, token=None, payload=None):
    url = f"{BASE_URL}{path}"
    body = None
    headers = {"Content-Type": "application/json"}
    if token:
        headers["Authorization"] = f"Bearer {token}"
    if payload is not None:
        body = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(url, data=body, headers=headers, method=method)
    try:
        with urllib.request.urlopen(req, timeout=20) as resp:
            text = resp.read().decode("utf-8")
            return resp.status, json.loads(text) if text else {}
    except urllib.error.HTTPError as e:
        text = e.read().decode("utf-8")
        try:
            data = json.loads(text) if text else {}
        except json.JSONDecodeError:
            data = {"raw": text}
        return e.code, data


def register_or_login(username, email, password, full_name=None):
    reg_payload = {"username": username, "email": email, "password": password}
    if full_name:
        reg_payload["full_name"] = full_name
    status, _ = api_request("POST", "/auth/register", payload=reg_payload)
    if status not in (200, 201, 409):
        # Registration failed unexpectedly; still try login.
        pass
    login_status, login_data = api_request(
        "POST",
        "/auth/login",
        payload={"username": username, "password": password},
    )
    if login_status != 200:
        raise RuntimeError(f"login failed for {username}: {login_status} {login_data}")
    tokens = login_data["data"]["tokens"]
    user = login_data["data"]["user"]
    return tokens["access_token"], user


def ensure_family(owner_token):
    status, mine = api_request("GET", "/families/mine", token=owner_token)
    if status != 200:
        raise RuntimeError(f"query my family failed: {status} {mine}")
    fam = mine.get("data", {}).get("family")
    if fam:
        return fam
    create_payload = {
        "name": "Demo Family",
        "default_currency": "CNY",
        "description": "Autogenerated demo family data",
        "nickname": "Owner",
    }
    c_status, c_data = api_request("POST", "/families", token=owner_token, payload=create_payload)
    if c_status not in (200, 201):
        raise RuntimeError(f"create family failed: {c_status} {c_data}")
    return c_data["data"]["family"]


def ensure_member_join(user_token, invite_code, nickname):
    status, mine = api_request("GET", "/families/mine", token=user_token)
    if status == 200 and mine.get("data", {}).get("family"):
        return
    j_status, j_data = api_request(
        "POST",
        "/families/join",
        token=user_token,
        payload={"invite_code": invite_code, "nickname": nickname},
    )
    if j_status not in (200, 201, 409):
        raise RuntimeError(f"join family failed: {j_status} {j_data}")


def pick_categories(token):
    status, data = api_request("GET", "/categories", token=token)
    if status != 200:
        raise RuntimeError(f"list categories failed: {status} {data}")
    cats = data.get("data", {}).get("categories", [])
    flat = []
    for c in cats:
        flat.append(c)
        for ch in c.get("children", []):
            flat.append(ch)
    expense = next((c for c in flat if c.get("type") == "expense"), None)
    income = next((c for c in flat if c.get("type") == "income"), None)
    if not expense or not income:
        raise RuntimeError("missing system categories")
    return expense["id"], income["id"]


def create_account(token, name, account_type, initial_balance, family_id=None):
    payload = {
        "name": name,
        "type": account_type,
        "currency": "CNY",
        "initial_balance": float(initial_balance),
    }
    if family_id:
        payload["family_id"] = str(family_id)
        payload["visibility"] = "family"
    status, data = api_request("POST", "/accounts", token=token, payload=payload)
    if status not in (200, 201):
        raise RuntimeError(f"create account failed: {status} {data}")
    return data["data"]["id"]


def create_budget(token, family_id, account_ids, category_ids):
    today = datetime.now(timezone.utc).date()
    start = today.replace(day=1).isoformat()
    end = (today + timedelta(days=28)).isoformat()
    payload = {
        "name": "Family Monthly Budget",
        "type": "monthly",
        "start_date": start,
        "end_date": end,
        "amount": 18000,
        "currency": "CNY",
        "category_ids": category_ids,
        "account_ids": account_ids,
        "family_id": str(family_id),
        "scope": "family",
        "alert_threshold": 0.75,
    }
    status, data = api_request("POST", "/budgets", token=token, payload=payload)
    if status not in (200, 201):
        raise RuntimeError(f"create budget failed: {status} {data}")
    return data["data"]["id"]


def create_transactions(token, family_id, cash_account_id, card_account_id, expense_cat, income_cat):
    tx_ids = []
    now = datetime.now(timezone.utc)

    # Income
    for i in range(3):
        dt = (now - timedelta(days=25 - i * 10)).replace(hour=9, minute=30, second=0, microsecond=0)
        payload = {
            "type": "income",
            "amount": 8000 + i * 1200,
            "currency": "CNY",
            "account_id": cash_account_id,
            "category_id": income_cat,
            "description": f"Salary #{i+1}",
            "payee": "Employer",
            "transaction_date": dt.isoformat().replace("+00:00", "Z"),
            "tags": ["salary", "demo"],
            "family_id": str(family_id),
        }
        status, data = api_request("POST", "/transactions", token=token, payload=payload)
        if status in (200, 201):
            tx_ids.append(data["data"]["id"])

    # Expense
    merchants = ["Supermarket", "Coffee Shop", "Online Store", "Gas Station", "Restaurant"]
    for i in range(14):
        dt = (now - timedelta(days=i)).replace(hour=18, minute=15, second=0, microsecond=0)
        payload = {
            "type": "expense",
            "amount": float(random.randint(30, 420)),
            "currency": "CNY",
            "account_id": cash_account_id if i % 2 == 0 else card_account_id,
            "category_id": expense_cat,
            "description": f"Family expense #{i+1}",
            "payee": merchants[i % len(merchants)],
            "transaction_date": dt.isoformat().replace("+00:00", "Z"),
            "tags": ["daily", "demo"],
            "family_id": str(family_id),
        }
        status, data = api_request("POST", "/transactions", token=token, payload=payload)
        if status in (200, 201):
            tx_ids.append(data["data"]["id"])

    # Transfer
    dt = now.replace(hour=21, minute=0, second=0, microsecond=0)
    payload = {
        "type": "transfer",
        "amount": 1500.0,
        "currency": "CNY",
        "account_id": cash_account_id,
        "to_account_id": card_account_id,
        "category_id": expense_cat,
        "description": "Cash to card transfer",
        "transaction_date": dt.isoformat().replace("+00:00", "Z"),
        "tags": ["transfer", "demo"],
        "family_id": str(family_id),
    }
    status, data = api_request("POST", "/transactions", token=token, payload=payload)
    if status in (200, 201):
        tx_ids.append(data["data"]["id"])
    return tx_ids


def main():
    random.seed(42)
    owner_token, owner_user = register_or_login(
        OWNER_USERNAME,
        f"{OWNER_USERNAME}@example.com",
        OWNER_PASSWORD,
        OWNER_USERNAME,
    )
    family = ensure_family(owner_token)
    family_id = family["id"]
    invite_code = family["invite_code"]

    seeded_users = [owner_user["username"]]
    for u in DEMO_USERS:
        token, user = register_or_login(u["username"], u["email"], DEMO_PASSWORD, u["full_name"])
        ensure_member_join(token, invite_code, u["full_name"].split()[0])
        seeded_users.append(user["username"])

    expense_cat, income_cat = pick_categories(owner_token)
    family_cash = create_account(owner_token, "Family Cash", "cash", 25000, family_id=family_id)
    family_card = create_account(owner_token, "Family Card", "credit_card", 0, family_id=family_id)
    create_account(owner_token, "Owner Wallet", "cash", 1800)

    tx_ids = create_transactions(
        owner_token,
        family_id,
        family_cash,
        family_card,
        expense_cat,
        income_cat,
    )
    budget_id = create_budget(owner_token, family_id, [family_cash, family_card], [expense_cat, income_cat])

    print(json.dumps({
        "ok": True,
        "gateway": BASE_URL,
        "family_id": family_id,
        "invite_code": invite_code,
        "seeded_users": seeded_users,
        "accounts_created": [family_cash, family_card],
        "transactions_created": len(tx_ids),
        "budget_id": budget_id
    }, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
